# Generated by Django 5.0.6 on 2024-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tip',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
