# Generated by Django 5.0.6 on 2024-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tip_firebase_id_alter_tip_twitter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='firebase_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
