# Generated by Django 5.0.6 on 2024-08-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tip_firebase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
