# Generated by Django 5.0.6 on 2024-08-24 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tip_firebase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='firebase_id',
        ),
        migrations.AlterField(
            model_name='tip',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
